import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../component/footer'
import Headline from '../component/headline'
import Main from '../component/main'
import React, {Component} from 'react'
import QuestBox from '../component/questBox'

export default function About() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Main page="About" />
      <QuestBox></QuestBox>

      <Footer/>
      
    </div>
  )
}
